spring.datasource.url={$DB_URL:jdbc:postgres://localhost:5432/playground}
spring.datasource.user={$DB_USER:ladi}
spring.datasource.password={$DB_PASSWORD:oladipupo}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
